// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "From the movie detail on go swagger.io",
    "title": "Movie",
    "version": "0.1.0"
  },
  "paths": {
    "/login": {
      "post": {
        "description": "Login user by email and phone number",
        "tags": [
          "user"
        ],
        "summary": "login user by given email and phone.",
        "parameters": [
          {
            "description": "Login user by given payload",
            "name": "Login",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Login"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "login the user operations",
            "schema": {
              "$ref": "#/definitions/LoginSuccess"
            }
          },
          "default": {
            "description": "failed to login user",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/movie/create": {
      "post": {
        "description": "create movie by given fields is title and genre",
        "tags": [
          "movie"
        ],
        "summary": "create movie by given payload.",
        "parameters": [
          {
            "description": "create movie with the input payload.",
            "name": "movie",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/movie"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "create the movie operations",
            "schema": {
              "$ref": "#/definitions/movie"
            }
          },
          "default": {
            "description": "failed to create movie",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/movie/get": {
      "get": {
        "description": "get movie by the given movie id.",
        "tags": [
          "movie"
        ],
        "summary": "get movie by given id.",
        "parameters": [
          {
            "type": "string",
            "description": "get movie by given id",
            "name": "id",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "get the movie operations",
            "schema": {
              "$ref": "#/definitions/movie"
            }
          },
          "default": {
            "description": "failed to get movie",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/user/create": {
      "post": {
        "description": "create user by given fields",
        "tags": [
          "user"
        ],
        "summary": "create user by given payload.",
        "parameters": [
          {
            "description": "create user with given input payload",
            "name": "Register",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Register"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "create the user operations",
            "schema": {
              "$ref": "#/definitions/Register"
            }
          },
          "default": {
            "description": "failed to create user",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Login": {
      "type": "object",
      "required": [
        "UserEmail",
        "UserPhone"
      ],
      "properties": {
        "UserEmail": {
          "type": "string",
          "format": "abc@gmail.com"
        },
        "UserPhone": {
          "type": "string",
          "maxLength": 10,
          "minLength": 10
        }
      }
    },
    "LoginSuccess": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "token": {
          "type": "string"
        }
      }
    },
    "Register": {
      "type": "object",
      "required": [
        "Name",
        "Email",
        "Phone",
        "DOB"
      ],
      "properties": {
        "Address": {
          "type": "string",
          "minLength": 2
        },
        "DOB": {
          "type": "string",
          "format": "yyyy-mm-dd"
        },
        "Email": {
          "type": "string",
          "format": "abc@gmail.com"
        },
        "Name": {
          "type": "string",
          "minLength": 2
        },
        "Phone": {
          "type": "string",
          "maxLength": 10,
          "minLength": 10
        },
        "userId": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "movie": {
      "type": "object",
      "required": [
        "title"
      ],
      "properties": {
        "genre": {
          "type": "string",
          "minLength": 2
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "title": {
          "type": "string",
          "minLength": 2
        }
      }
    }
  },
  "securityDefinitions": {
    "key": {
      "type": "apiKey",
      "name": "x-token",
      "in": "header"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "From the movie detail on go swagger.io",
    "title": "Movie",
    "version": "0.1.0"
  },
  "paths": {
    "/login": {
      "post": {
        "description": "Login user by email and phone number",
        "tags": [
          "user"
        ],
        "summary": "login user by given email and phone.",
        "parameters": [
          {
            "description": "Login user by given payload",
            "name": "Login",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Login"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "login the user operations",
            "schema": {
              "$ref": "#/definitions/LoginSuccess"
            }
          },
          "default": {
            "description": "failed to login user",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/movie/create": {
      "post": {
        "description": "create movie by given fields is title and genre",
        "tags": [
          "movie"
        ],
        "summary": "create movie by given payload.",
        "parameters": [
          {
            "description": "create movie with the input payload.",
            "name": "movie",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/movie"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "create the movie operations",
            "schema": {
              "$ref": "#/definitions/movie"
            }
          },
          "default": {
            "description": "failed to create movie",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/movie/get": {
      "get": {
        "description": "get movie by the given movie id.",
        "tags": [
          "movie"
        ],
        "summary": "get movie by given id.",
        "parameters": [
          {
            "type": "string",
            "description": "get movie by given id",
            "name": "id",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "get the movie operations",
            "schema": {
              "$ref": "#/definitions/movie"
            }
          },
          "default": {
            "description": "failed to get movie",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/user/create": {
      "post": {
        "description": "create user by given fields",
        "tags": [
          "user"
        ],
        "summary": "create user by given payload.",
        "parameters": [
          {
            "description": "create user with given input payload",
            "name": "Register",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Register"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "create the user operations",
            "schema": {
              "$ref": "#/definitions/Register"
            }
          },
          "default": {
            "description": "failed to create user",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Login": {
      "type": "object",
      "required": [
        "UserEmail",
        "UserPhone"
      ],
      "properties": {
        "UserEmail": {
          "type": "string",
          "format": "abc@gmail.com"
        },
        "UserPhone": {
          "type": "string",
          "maxLength": 10,
          "minLength": 10
        }
      }
    },
    "LoginSuccess": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "token": {
          "type": "string"
        }
      }
    },
    "Register": {
      "type": "object",
      "required": [
        "Name",
        "Email",
        "Phone",
        "DOB"
      ],
      "properties": {
        "Address": {
          "type": "string",
          "minLength": 2
        },
        "DOB": {
          "type": "string",
          "format": "yyyy-mm-dd"
        },
        "Email": {
          "type": "string",
          "format": "abc@gmail.com"
        },
        "Name": {
          "type": "string",
          "minLength": 2
        },
        "Phone": {
          "type": "string",
          "maxLength": 10,
          "minLength": 10
        },
        "userId": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "movie": {
      "type": "object",
      "required": [
        "title"
      ],
      "properties": {
        "genre": {
          "type": "string",
          "minLength": 2
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "title": {
          "type": "string",
          "minLength": 2
        }
      }
    }
  },
  "securityDefinitions": {
    "key": {
      "type": "apiKey",
      "name": "x-token",
      "in": "header"
    }
  }
}`))
}
