// Code generated by go-swagger; DO NOT EDIT.

package movie

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMovieGetParams creates a new GetMovieGetParams object
// with the default values initialized.
func NewGetMovieGetParams() *GetMovieGetParams {
	var ()
	return &GetMovieGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMovieGetParamsWithTimeout creates a new GetMovieGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMovieGetParamsWithTimeout(timeout time.Duration) *GetMovieGetParams {
	var ()
	return &GetMovieGetParams{

		timeout: timeout,
	}
}

// NewGetMovieGetParamsWithContext creates a new GetMovieGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMovieGetParamsWithContext(ctx context.Context) *GetMovieGetParams {
	var ()
	return &GetMovieGetParams{

		Context: ctx,
	}
}

// NewGetMovieGetParamsWithHTTPClient creates a new GetMovieGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMovieGetParamsWithHTTPClient(client *http.Client) *GetMovieGetParams {
	var ()
	return &GetMovieGetParams{
		HTTPClient: client,
	}
}

/*
GetMovieGetParams contains all the parameters to send to the API endpoint
for the get movie get operation typically these are written to a http.Request
*/
type GetMovieGetParams struct {

	/*ID
	  get movie by given id

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get movie get params
func (o *GetMovieGetParams) WithTimeout(timeout time.Duration) *GetMovieGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get movie get params
func (o *GetMovieGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get movie get params
func (o *GetMovieGetParams) WithContext(ctx context.Context) *GetMovieGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get movie get params
func (o *GetMovieGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get movie get params
func (o *GetMovieGetParams) WithHTTPClient(client *http.Client) *GetMovieGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get movie get params
func (o *GetMovieGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get movie get params
func (o *GetMovieGetParams) WithID(id string) *GetMovieGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get movie get params
func (o *GetMovieGetParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetMovieGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param id
	qrID := o.ID
	qID := qrID
	if qID != "" {
		if err := r.SetQueryParam("id", qID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
