// Code generated by go-swagger; DO NOT EDIT.

package movie

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new movie API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for movie API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetMovieGet(params *GetMovieGetParams) (*GetMovieGetOK, error)

	PostMovieCreate(params *PostMovieCreateParams) (*PostMovieCreateOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetMovieGet gets movie by given id

get movie by the given movie id.
*/
func (a *Client) GetMovieGet(params *GetMovieGetParams) (*GetMovieGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetMovieGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetMovieGet",
		Method:             "GET",
		PathPattern:        "/movie/get",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetMovieGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetMovieGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetMovieGetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostMovieCreate creates movie by given payload

create movie by given fields is title and genre
*/
func (a *Client) PostMovieCreate(params *PostMovieCreateParams) (*PostMovieCreateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostMovieCreateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PostMovieCreate",
		Method:             "POST",
		PathPattern:        "/movie/create",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostMovieCreateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostMovieCreateOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*PostMovieCreateDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
