// Code generated by go-swagger; DO NOT EDIT.

package movie

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"go-swagger/models"
)

// NewPostMovieCreateParams creates a new PostMovieCreateParams object
// with the default values initialized.
func NewPostMovieCreateParams() *PostMovieCreateParams {
	var ()
	return &PostMovieCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostMovieCreateParamsWithTimeout creates a new PostMovieCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostMovieCreateParamsWithTimeout(timeout time.Duration) *PostMovieCreateParams {
	var ()
	return &PostMovieCreateParams{

		timeout: timeout,
	}
}

// NewPostMovieCreateParamsWithContext creates a new PostMovieCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostMovieCreateParamsWithContext(ctx context.Context) *PostMovieCreateParams {
	var ()
	return &PostMovieCreateParams{

		Context: ctx,
	}
}

// NewPostMovieCreateParamsWithHTTPClient creates a new PostMovieCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostMovieCreateParamsWithHTTPClient(client *http.Client) *PostMovieCreateParams {
	var ()
	return &PostMovieCreateParams{
		HTTPClient: client,
	}
}

/*
PostMovieCreateParams contains all the parameters to send to the API endpoint
for the post movie create operation typically these are written to a http.Request
*/
type PostMovieCreateParams struct {

	/*Movie
	  create movie with the input payload.

	*/
	Movie *models.Movie

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post movie create params
func (o *PostMovieCreateParams) WithTimeout(timeout time.Duration) *PostMovieCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post movie create params
func (o *PostMovieCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post movie create params
func (o *PostMovieCreateParams) WithContext(ctx context.Context) *PostMovieCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post movie create params
func (o *PostMovieCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post movie create params
func (o *PostMovieCreateParams) WithHTTPClient(client *http.Client) *PostMovieCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post movie create params
func (o *PostMovieCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMovie adds the movie to the post movie create params
func (o *PostMovieCreateParams) WithMovie(movie *models.Movie) *PostMovieCreateParams {
	o.SetMovie(movie)
	return o
}

// SetMovie adds the movie to the post movie create params
func (o *PostMovieCreateParams) SetMovie(movie *models.Movie) {
	o.Movie = movie
}

// WriteToRequest writes these params to a swagger request
func (o *PostMovieCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Movie != nil {
		if err := r.SetBodyParam(o.Movie); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
