// Code generated by go-swagger; DO NOT EDIT.

package movie

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"go-swagger/models"
)

// GetMovieGetOKCode is the HTTP code returned for type GetMovieGetOK
const GetMovieGetOKCode int = 200

/*
GetMovieGetOK get the movie operations

swagger:response getMovieGetOK
*/
type GetMovieGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.Movie `json:"body,omitempty"`
}

// NewGetMovieGetOK creates GetMovieGetOK with default headers values
func NewGetMovieGetOK() *GetMovieGetOK {

	return &GetMovieGetOK{}
}

// WithPayload adds the payload to the get movie get o k response
func (o *GetMovieGetOK) WithPayload(payload *models.Movie) *GetMovieGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get movie get o k response
func (o *GetMovieGetOK) SetPayload(payload *models.Movie) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMovieGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetMovieGetDefault failed to get movie

swagger:response getMovieGetDefault
*/
type GetMovieGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetMovieGetDefault creates GetMovieGetDefault with default headers values
func NewGetMovieGetDefault(code int) *GetMovieGetDefault {
	if code <= 0 {
		code = 500
	}

	return &GetMovieGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get movie get default response
func (o *GetMovieGetDefault) WithStatusCode(code int) *GetMovieGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get movie get default response
func (o *GetMovieGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get movie get default response
func (o *GetMovieGetDefault) WithPayload(payload *models.Error) *GetMovieGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get movie get default response
func (o *GetMovieGetDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMovieGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
