// Code generated by go-swagger; DO NOT EDIT.

package movie

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetMovieGetHandlerFunc turns a function with the right signature into a get movie get handler
type GetMovieGetHandlerFunc func(GetMovieGetParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMovieGetHandlerFunc) Handle(params GetMovieGetParams) middleware.Responder {
	return fn(params)
}

// GetMovieGetHandler interface for that can handle valid get movie get params
type GetMovieGetHandler interface {
	Handle(GetMovieGetParams) middleware.Responder
}

// NewGetMovieGet creates a new http.Handler for the get movie get operation
func NewGetMovieGet(ctx *middleware.Context, handler GetMovieGetHandler) *GetMovieGet {
	return &GetMovieGet{Context: ctx, Handler: handler}
}

/*
GetMovieGet swagger:route GET /movie/get movie getMovieGet

get movie by given id.

get movie by the given movie id.
*/
type GetMovieGet struct {
	Context *middleware.Context
	Handler GetMovieGetHandler
}

func (o *GetMovieGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetMovieGetParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
