// Code generated by go-swagger; DO NOT EDIT.

package movie

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetMovieGetIDHandlerFunc turns a function with the right signature into a get movie get ID handler
type GetMovieGetIDHandlerFunc func(GetMovieGetIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMovieGetIDHandlerFunc) Handle(params GetMovieGetIDParams) middleware.Responder {
	return fn(params)
}

// GetMovieGetIDHandler interface for that can handle valid get movie get ID params
type GetMovieGetIDHandler interface {
	Handle(GetMovieGetIDParams) middleware.Responder
}

// NewGetMovieGetID creates a new http.Handler for the get movie get ID operation
func NewGetMovieGetID(ctx *middleware.Context, handler GetMovieGetIDHandler) *GetMovieGetID {
	return &GetMovieGetID{Context: ctx, Handler: handler}
}

/*
GetMovieGetID swagger:route GET /movie/get/{id} movie getMovieGetId

get movie by given id.

get movie by the given movie id.
*/
type GetMovieGetID struct {
	Context *middleware.Context
	Handler GetMovieGetIDHandler
}

func (o *GetMovieGetID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetMovieGetIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
