// Code generated by go-swagger; DO NOT EDIT.

package movie

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"go-swagger/models"
)

// NewPostMovieCreateParams creates a new PostMovieCreateParams object
// no default values defined in spec.
func NewPostMovieCreateParams() PostMovieCreateParams {

	return PostMovieCreateParams{}
}

// PostMovieCreateParams contains all the bound params for the post movie create operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostMovieCreate
type PostMovieCreateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*create movie with the input payload.
	  Required: true
	  In: body
	*/
	Movie *models.Movie
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostMovieCreateParams() beforehand.
func (o *PostMovieCreateParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Movie
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("movie", "body", ""))
			} else {
				res = append(res, errors.NewParseError("movie", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Movie = &body
			}
		}
	} else {
		res = append(res, errors.Required("movie", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
