// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Login login
//
// swagger:model Login
type Login struct {

	// user email
	// Required: true
	UserEmail *string `json:"UserEmail"`

	// user phone
	// Required: true
	// Max Length: 10
	// Min Length: 10
	UserPhone *string `json:"UserPhone"`
}

// Validate validates this login
func (m *Login) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUserEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserPhone(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Login) validateUserEmail(formats strfmt.Registry) error {

	if err := validate.Required("UserEmail", "body", m.UserEmail); err != nil {
		return err
	}

	return nil
}

func (m *Login) validateUserPhone(formats strfmt.Registry) error {

	if err := validate.Required("UserPhone", "body", m.UserPhone); err != nil {
		return err
	}

	if err := validate.MinLength("UserPhone", "body", string(*m.UserPhone), 10); err != nil {
		return err
	}

	if err := validate.MaxLength("UserPhone", "body", string(*m.UserPhone), 10); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Login) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Login) UnmarshalBinary(b []byte) error {
	var res Login
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
